# Generated by Django 4.0.6 on 2022-07-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=256)),
                ('username', models.CharField(max_length=25)),
                ('siteurl', models.CharField(max_length=100)),
            ],
        ),
    ]
