# Generated by Django 4.0.6 on 2022-07-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchdetails',
            name='siteurl',
            field=models.CharField(max_length=256),
        ),
    ]
